### ISSUE TITLE
generate .osu file from Beatmap

### ISSUE THREAD

**Issue by IMXZ1234** [llllllllll/slider#100]
It seems that ``Beatmap`` does not provides a ``to_file`` function to generate .osu files from ``Beatmap`` instances. Besides, since ``curve.py`` is not directly visible to the outside, it is difficult to determine the class type(e.g. Bezier or Linear) of ``Slider.curve`` in order to decide how to generate its str(e.g. whether 'B' or 'L' should be used) in .osu file, making it difficult to generate .osu file solely using slider's current exposed api. How about adding this functionality? I'm willing to work on the implementation if this is to be added.

**Comment by tybug** [comment]
The ability to write beatmaps back to files would be useful. The api should probably mimic the existing `Beatmap.from_{path, file}` methods by adding `Beatmap#write_{path, file}` methods, and also a `Beatmap#pack` method which returns the string content which would be written to the file.

For the record, you can always import the curve types directly (`from slider.curve import ...`), but I agree it's probably a good idea to expose these classes directly through `__init__.py`.

A PR for these changes would be welcome :)

**Comment by tybug** [comment]
closed by #101
