### ISSUE TITLE
Slider FOLLOW_AREA

### ISSUE THREAD

**Issue by Vergenter** [llllllllll/slider#120]
In this line, the FOLLOW_AREA of the slider is assumed to be 3. Is there a specific reason for this?
https://github.com/llllllllll/slider/blob/d70dc7d2a3a158edb3477b5b2f361131827e56eb/slider/replay.py#L165
In the osu!lazer repository, it is set to 2.4f:
https://github.com/ppy/osu/blob/3793a552b8756ae19722382879af72156f039cec/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSliderBall.cs#L21
### Other Player Analysis
>  7 years ago
~2.4x circle radius based on my tests.

Source: Drezi from https://osu.ppy.sh/community/forums/topics/604682?n=4
#### Furthest Successful Hit
![hit1](https://github.com/llllllllll/slider/assets/37329111/c5ba7404-043e-4113-b0fd-ee2a3e5c7e2b)
![hit2](https://github.com/llllllllll/slider/assets/37329111/d256c004-8fb5-4afe-b35b-c85be587e33e)
The follow circle expanded on a slider tick, and the score was judged.
Circle size: 72px ± 5px
Distance from slider tick to cursor: 171px ± 2px
171 / 72= 2.375, which is less than 2.4
#### Nearest miss
![miss1](https://github.com/llllllllll/slider/assets/37329111/b364ecee-e7a1-49a4-a834-b00f18130c33)
![miss2](https://github.com/llllllllll/slider/assets/37329111/dccda668-99e4-493f-8aeb-3f907a55a06a)
The follow circle expanded on a slider tick, and the slider tick miss animation started (cross began to fade in).
Circle size: 72px ± 5px
Distance from slider tick to cursor: 175px ± 2px
175 / 72 = 2.43 , which is greater than 2.4

Therefore, the FOLLOW_AREA should be set to 2.4.

**Comment by tybug** [comment]
Thanks, I think you're right. Replay calculation has never been perfect in slider and this is probably one of several reasons why. I've fixed this in https://github.com/llllllllll/slider/commit/3b6659c0caff379f373373012599036bce5717ee.
