### ISSUE TITLE
_lzma module not in linux

### ISSUE THREAD

**Issue by de-odex** [llllllllll/slider#2]
So, I've been getting a "No module called '_lzma'" in my rpi with slider installed, python 3.6.1

**Comment by llllllllll** [comment]
How did you install Python 3.6? do you have `liblzma-dev` installed?

**Comment by de-odex** [comment]
i installed python normally, with apt-get (i dont recall its been a while since i installed)

**Comment by llllllllll** [comment]
On the server that hosts [combine](https://github.com/llllllllll/combine) I am running Ubuntu 16.04 with the following packages installed: https://github.com/llllllllll/combine/blob/master/fabfile.py#L47. I am getting Python3.6 from the deadsnakes PPA: https://github.com/llllllllll/combine/blob/master/fabfile.py#L46.

This configuration seems to work without any problems. On my laptop where I am developing slider I use Arch Linux and have the Python3.6 package from the core repo which also seems to work.

**Comment by de-odex** [comment]
Seems to be a raspberry pi issue... thanks for trying to help though

**Comment by llllllllll** [comment]
lzma does work on raspberry pi, if you are comfortable building your own Python, you can build a CPython with `lzma` using:

```bash
$ sudo apt install liblzma-dev
$ git clone git@github.com:python/cpython
$ cd cpython
$ ./configure --enable-shared
$ make
$ sudo make altinstall
```

**Comment by de-odex** [comment]
i mean, python 3.6.1 is not officially supported, but ill attempt your fix, thanks
