### ISSUE TITLE
get_center failing

### ISSUE THREAD

**Issue by blimmo** [llllllllll/slider#25]
On [this](https://osu.ppy.sh/b/794670) map this 3rd object is a perfect slider.

[Wolfram](https://www.wolframalpha.com/input/?i=centre+of+circle+passing+through+(175,+100),+(247,+80),+(319,+98)) predicts a center of `(248.763, 225.947)` which looks exactly correct, while the algorithm used in `get_center` is returning `(-38.115129441537569, -60.930918915221781)` which is clearly crazy (it's to the left of and above the first control point despite the slider curving down)

I've checked the algorithm against the osu source and it seems to be exactly the same so I have no idea how osu is getting the right answer and slider not.

**Comment by llllllllll** [comment]
this seems totally off, yeah. Do you think there is something special about this curve or are all P curves off?

**Comment by blimmo** [comment]
the next few sliders are fine but the 6th object is a similar slider and also completely broken

I get center:

`Position(x=0.59841441302418885, y=15.181194784151845)`

For points:

`[Position(x=392, y=312), Position(x=320, y=328), Position(x=249, y=308)]`

**Comment by blimmo** [comment]
It seems to be the longer P curves (in this map at least, I'll check another map now)

`Position(x=21.164330545047687, y=-50.990202994299111)`

`[Position(x=264, y=336), Position(x=239, y=251), Position(x=248, y=172)]`

**Comment by blimmo** [comment]
Got another with [this](https://osu.ppy.sh/b/1321495) map

1st object is a longish P slider and sure enough:

`Position(x=-24.442168157675727, y=-29.566110417506486)`

`[Position(x=164, y=96), Position(x=243, y=76), Position(x=300, y=87)]`

**Comment by blimmo** [comment]
Turns out the int32s being using in the calculations are overflowing (that's why only the longer sliders are failing)

I've made a fix and a PR for it (#26)
