### ISSUE TITLE
Spinner end_time is an int, not a timedelta

### ISSUE THREAD

**Issue by ScottSWu** [llllllllll/slider#35]
Thanks for writing this awesome library!

A small issue I encountered was that Spinner.end_time was an int and not timedelta.

https://github.com/llllllllll/slider/blob/master/slider/beatmap.py#L429

**Comment by blimmo** [comment]
Looks like a problem left over from changing to representing times as timedeltas. Should be a quick fix.

**Comment by llllllllll** [comment]
Thanks for reporting this. I just merged @blimmo's fix, thanks for getting to this so quickly!
