### ISSUE TITLE
doc uses .osz instead of .osr

### ISSUE THREAD

**Issue by InvisibleSymbol** [llllllllll/slider#52]
https://llllllllll.github.io/slider/replays

`*.osz` are [Executable beatmap files](https://osu.ppy.sh/help/wiki/osu!_File_Formats/Osz_(file_format)).
You want `*.osr` if you're talking about replays

Also the path is wrong, it's `osu!/data/r`, not `osu!/r.`

**Comment by llllllllll** [comment]
Thanks for noticing this. I believe it is just an issue in the docs, the replay parsing code properly accepts `osr` files. This is confusing, so the docs do need to be updated. Would you be interested in opening a pull request to fix this? The docs are located in this repo itself, in `docs/source` (this particular file is `docs/source/replays.rst`). The docs are written in restructured text, using sphinx, but for for a small change you should just be able to edit the file as plain text.
