### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by tybug** [llllllllll/slider#59]
Hey there. @jxu approached us recently (circleguard/circlecore#89) about using slider in Circleguard, and we fully intend to use it for beatmap parsing going forward. 

However -- the latest and only pypi version (0.1.0) was released on June 2nd 2017, more than two years ago. I'm not familiar enough with the history of this library to know how much has changed since then, but would you guys be willing to publish updates on a semi regular basis when things end up changing? I would feel more comfortable using the library if it wasn't hardstuck at version 0.1.0.

**Comment by jxu** [comment]
Any specific features you have in mind? I think most beatmap parsing has been implemented.

**Comment by tybug** [comment]
Nothing yet (beyond bugfixes like this https://github.com/llllllllll/slider/commit/77a08cd79274950811da5324a141bdc77e896f1e, though we aren't using pp calc). Just would ease my mind to know that if we did have something we wanted in a release, the maintainers of this repository would be able and willing to release to pypi.

**Comment by jxu** [comment]
I'm not sure what the current status is for pp calc - for now I would use oppai/pyttanko. @llllllllll is the author of the PyPI release so he should give you the answer.

**Comment by llllllllll** [comment]
I would love to have more people using and contributing to slider, but I don't know if I can personally commit to updating on a regular schedule. I would be willing to give PyPI access and commit access to @jxu or maybe one of the circleguard devs (or both) to make it easier to use slider. Code would still need to be reviewed by at least myself or @blimmo, but it seems like you have reasonable changes so it shouldn't be a big blocker.

If that sounds like a good plan, I can go over how to release on PyPI and we can do the first release together to make sure it goes smoothly.

**Comment by tybug** [comment]
Sounds good. I'm more than happy with @jxu having access and not us, so long as he feels comfortable with that anyway :)

**Comment by jxu** [comment]
I can try doing releases but I cannot guarantee adding features in a timely
manner.

**Comment by blimmo** [comment]
I should be able to do reviews within a day or two, although I'm not usually confident enough to merge stuff myself, I can certainly do that if @llllllllll is confident in my decision making. I'm also ok with doing releases if I'm needed.

**Comment by InvisibleSymbol** [comment]
Hi there, I'm also a dev from the circleguard team, and I'm responsible for upgrading our visualizer to use slider.
At first, I thought there were only minor changes between github and pypi, but after some investigation, I found some major changes that would require a new release for me to be able to use slider.

Those changes include:
- `collection.py` has been added (not used by me, but a major change)
- `curve.py` has been added (necessary for me to draw sliders)
- the cache/db logic has been reworked (`library.py`)
- `HitWindows` has been added to `mod.py`
- a new class called `Point` has been added to `position.py`
- `replay.py` has some QoL changes and a new function called `hits()`
- tick point calculation, some QoL changes, double_time/half_time arguments to some function and other things have been added to `beatmap.py`
- maybe even more...

Also just as a side note, is there anything holding you back from an 1.0 release?

**Comment by jxu** [comment]
1.0 sounds like an official release and there's not that much code coverage so IDK if the project can be considered stable 

I've been meaning to write more testing code but I've been busy sorry

**Comment by llllllllll** [comment]
Hey, yesterday I pushed up a 0.2.1 (realized pypi didn't have the readme for 0.2.0). I agree with @jxu's sentiment that 1.0.0 implies a more stable project than we currently have. I think getting a first set of tests would be enough to cut that release.

**Comment by tybug** [comment]
Going to close this since @llllllllll has added me as a maintainer to slider since this issue was opened, and even if I wasn't I don't have any remaining qualms about a release schedule.
