### ISSUE TITLE
PermissionError when using TemporaryDirectory with Library on Windows

### ISSUE THREAD

**Issue by tybug** [llllllllll/slider#60]
On windows systems,

```python
from slider import Library
from tempfile import TemporaryDirectory

temp_dir = TemporaryDirectory()
library = Library(temp_dir.name)
```

errors with a stacktrace of 

 ```sh
C:\Users\tybug>C:python slidertest.py
Traceback (most recent call last):
  File "C:\Users\tybug\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 628, in _exitfunc
    f()
  File "C:\Users\tybug\AppData\Local\Programs\Python\Python37\lib\weakref.py", line 552, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\tybug\AppData\Local\Programs\Python\Python37\lib\tempfile.py", line 795, in _cleanup
    _shutil.rmtree(name)
  File "C:\Users\tybug\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\tybug\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\tybug\AppData\Local\Programs\Python\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\tybug\\AppData\\Local\\Temp\\tmp_ak_r7tp\\.slider.db'
```

This code works fine on mac, and using a normal file that python does not remove on program exit works as expected. Interestingly, the order of `__del__` method calls is different per platform for otherwise identical code:

```
# osx
TemporaryDirectory.__del__ called
Library.__del__ called
```

```
# windows
Library.__del__ called
TemporaryDirectory.__del__ called
```

I don't know enough about python garbage collection and cleanup to say why this occurs, or if it's relevant. 

Windows: 8.1 and 10
slider: 0.2.0
python: 3.7.3

**Comment by llllllllll** [comment]
I think that the order of dels may be the same; however, macOS and GNU+Linux filesystems allow you to remove a directory while some of the constituent files are open. This is an issue that used to come up a lot in another project I worked on. The solution is to use the `Library` as a context manager such that the library is closed before the temporary directory is deleted. Then you don't need to worry about the destruction order of the objects. For example:

```python
with TemporaryDirectory() as temp_dir:
    # ...
    with Library(temp_dir.name) as library:
        # use the library
    # At this point, `library.close()` is called
# at this point, `os.unlink` is called but the files in the directory have been closed
```

You can also just manually call `library.close()`, but then you may still have cases where the temp dir tries to clean itself up before that happens, so I would recommend the context manager usage.

**Comment by InvisibleSymbol** [comment]
During my debugging I found a different solution, but I'm unsure if this is the correct solution/ something you want to have in your code... I guess it's better to share it than not.
@https://github.com/llllllllll/slider/blob/master/slider/library.py#L74
```python
...
        self._finalizer = _weakref.finalize(self, self._cleanup, self._read_beatmap, self._db)

    @classmethod
    def _cleanup(cls, bm, db):
        bm.cache_clear()
        db.close()
...
```

**Comment by tybug** [comment]
Context manager is unfortunately a no go since we want to keep `Library` around as an attribute in the `Circleguard` class. 

The main issue is that we don't have control over in exactly what order the objects are cleaned up, as `TemporaryDirectory` does that automatically. The solution we'll go with is to use `mkdtemp` and explicitly close the library before we remove it.

Closing as not a slider issue - the following code also reproduces this error, for instance:

```python
from tempfile import TemporaryDirectory
import sqlite3
class A():

    def __init__(self):
        self.temp_dir = TemporaryDirectory()
        open(self.temp_dir.name + "/db.db", 'a').close() # create db.db in temp dir
        self.db = sqlite3.connect(self.temp_dir.name + "/db.db")

    def __del__(self):
        self.db.close()

a = A()
```

**Comment by llllllllll** [comment]
You may be able to make your Circleguard class a context manager as well to make sure that you have deterministic cleanup of your resources.
