### ISSUE TITLE
random TypeError regarding beatmap_ID when only using the user api's

### ISSUE THREAD

**Issue by GDcheeriosYT** [llllllllll/slider#93]
I never use anything other than the user api portion and this has happened before but it randomly raises TypeError when I run the code. I don't understand why its talking about the beatmap_id when im only using the user portion
       
       
       
![image](https://user-images.githubusercontent.com/54640414/128609239-bc09567a-9765-4ec4-94ff-6302ae052ce9.png)

       
        }

     [Open an interactive python shell in this frame]  

        def _parse_user_events(events, _parse_date=_parse_date):

            out = []

            for event in events:

                event['beatmap_id'] = int(event['beatmap_id'])

                event['date'] = _parse_date(event['date'])

                event['epic_factor'] = event.pop('epicfactor')

                out.append(event)

     

            return out

    TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by tybug** [comment]
What user id are you retrieving when this error occurs?

**Comment by GDcheeriosYT** [comment]
its in a list

**Comment by GDcheeriosYT** [comment]
it would happen when I used margaritamix08 and or GDcheerios

**Comment by tybug** [comment]
Thanks for the report. This happens when the user has a supporter event in their recent events. Will be fixed by the above pr

**Comment by GDcheeriosYT** [comment]
when does this update?

**Comment by tybug** [comment]
wihtin a few days or so
